### ISSUE TITLE
TAC Life Support Tanks

### ISSUE THREAD

**Issue by PadroneSF** [Tidal-Stream/ProceduralParts#10]
I noticed that ThunderAerospace life support tanks were not showing in my Career game.  (They should appear early on, once "Survivability" is unlocked.

Troubleshooting lead me to the "TankLifeSupport.cfg" file in the ..\Parts\ZOtherMods folder.  

I believe the NEEDS statement should be changed to:

    PART:NEEDS[ThunderAerospace] 

instead of PART:NEEDS[TacLifeSupport]

Making this change manually in the CFG file fixed this issue for me.

**Comment by Tidal-Stream** [comment]
This is interesting because the plugin is `TacLifeSupport.dll`. How is this handled by other mods?

**Comment by PadroneSF** [comment]
Hmm, my bad!  I forgot I was also trying to track down a problem with [Filter Extensions](https://forum.kerbalspaceprogram.com/index.php?/topic/168456-15-filter-extensions-no-localization/).  I conflated the two issues.  Sloppy on my part.

The REAL issue appears to be that the "Mod_ProceduralParts.cfg" in "..GameData\000_FilterExtensions_Configs\Default" doesn't have a Utility category.  Since that tank is marked as Utility, the tank didn't show up (since its category didn't exist).  

I'm still working on a clean test case for that, so I can let LinuxGuruGamer know.

I'll go ahead and close this since my suggestion above isn't needed, either NEEDS statement works.
