### ISSUE TITLE
Red SRB Nozzle

### ISSUE THREAD

**Issue by rsparkyc** [Tidal-Stream/ProceduralParts#6]
I've seen this is the other screenshots in other bugs, but why is the nozzle for an SRB bright red?

**Comment by Tidal-Stream** [comment]
I am not sure why it is red, and I think the same bug is present in the Starwaster version. I think the problem should be in the SRB nozzle model, in the emissive shader part that changes its colour with increasing temperature.

**Comment by rsparkyc** [comment]
Looks like this is addressed by https://github.com/Tidal-Stream/ProceduralParts/pull/8 and https://github.com/Tidal-Stream/ProceduralParts/pull/7

**Comment by rsparkyc** [comment]
Actually addressed by https://github.com/Tidal-Stream/ProceduralParts/pull/9

**Comment by Tidal-Stream** [comment]
This was resolved with #9 that was merged with commit a8499b8.
